---
abstract: 'Catalyst view to convert HTML (or TT) content to PDF using wkhtmltopdf'
author:
  - 'Michele Beltrame <mb@italpro.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Wkhtmltopdf
requires:
  Catalyst::View::TT: 0
  File::Temp: 0
  URI::Escape: 0
version: 0.0004
